// Code generated by MockGen. DO NOT EDIT.
// Source: upload-avatar.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAvatarUsecase is a mock of AvatarUsecase interface.
type MockAvatarUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarUsecaseMockRecorder
}

// MockAvatarUsecaseMockRecorder is the mock recorder for MockAvatarUsecase.
type MockAvatarUsecaseMockRecorder struct {
	mock *MockAvatarUsecase
}

// NewMockAvatarUsecase creates a new mock instance.
func NewMockAvatarUsecase(ctrl *gomock.Controller) *MockAvatarUsecase {
	mock := &MockAvatarUsecase{ctrl: ctrl}
	mock.recorder = &MockAvatarUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarUsecase) EXPECT() *MockAvatarUsecaseMockRecorder {
	return m.recorder
}

// UploadAvatar mocks base method.
func (m *MockAvatarUsecase) UploadAvatar(ctx context.Context, userID string, file io.Reader, size int64, originalFilename string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, file, size, originalFilename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockAvatarUsecaseMockRecorder) UploadAvatar(ctx, userID, file, size, originalFilename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockAvatarUsecase)(nil).UploadAvatar), ctx, userID, file, size, originalFilename)
}

// MockProfileUsecase is a mock of ProfileUsecase interface.
type MockProfileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockProfileUsecaseMockRecorder
}

// MockProfileUsecaseMockRecorder is the mock recorder for MockProfileUsecase.
type MockProfileUsecaseMockRecorder struct {
	mock *MockProfileUsecase
}

// NewMockProfileUsecase creates a new mock instance.
func NewMockProfileUsecase(ctrl *gomock.Controller) *MockProfileUsecase {
	mock := &MockProfileUsecase{ctrl: ctrl}
	mock.recorder = &MockProfileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileUsecase) EXPECT() *MockProfileUsecaseMockRecorder {
	return m.recorder
}

// InsertProfileAvatar mocks base method.
func (m *MockProfileUsecase) InsertProfileAvatar(ctx context.Context, profileID int64, avatarURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertProfileAvatar", ctx, profileID, avatarURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertProfileAvatar indicates an expected call of InsertProfileAvatar.
func (mr *MockProfileUsecaseMockRecorder) InsertProfileAvatar(ctx, profileID, avatarURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertProfileAvatar", reflect.TypeOf((*MockProfileUsecase)(nil).InsertProfileAvatar), ctx, profileID, avatarURL)
}
