version: "2"

run:
  timeout: 5m
  tests: false


linters:
  enable:
    - gosimple     # Упрощение кода
    - govet        # Стандартный go vet
    - ineffassign  # Обнаружение бесполезных присваиваний
    - staticcheck  # Огромный набор статических проверок
    - typecheck    # Проверка типов
