version: "2"

run:
  timeout: 5m
  tests: false


linters:
  enable:
    - gosimple     # Упрощение кода
    - govet        # Стандартный go vet
    - ineffassign  # Обнаружение бесполезных присваиваний
    - typecheck    # Проверка типов
  disable:
    - unused       # Отключаем проверку неиспользуемого кода
    - errcheck     # Отключаем проверку необработанных ошибок
