// Code generated by MockGen. DO NOT EDIT.
// Source: send.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageUsecase is a mock of MessageUsecase interface.
type MockMessageUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMessageUsecaseMockRecorder
}

// MockMessageUsecaseMockRecorder is the mock recorder for MockMessageUsecase.
type MockMessageUsecaseMockRecorder struct {
	mock *MockMessageUsecase
}

// NewMockMessageUsecase creates a new mock instance.
func NewMockMessageUsecase(ctrl *gomock.Controller) *MockMessageUsecase {
	mock := &MockMessageUsecase{ctrl: ctrl}
	mock.recorder = &MockMessageUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageUsecase) EXPECT() *MockMessageUsecaseMockRecorder {
	return m.recorder
}

// SaveFile mocks base method.
func (m *MockMessageUsecase) SaveFile(ctx context.Context, messageID int64, fileName, fileType, storagePath string, size int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", ctx, messageID, fileName, fileType, storagePath, size)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveFile indicates an expected call of SaveFile.
func (mr *MockMessageUsecaseMockRecorder) SaveFile(ctx, messageID, fileName, fileType, storagePath, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockMessageUsecase)(nil).SaveFile), ctx, messageID, fileName, fileType, storagePath, size)
}

// SaveMessage mocks base method.
func (m *MockMessageUsecase) SaveMessage(ctx context.Context, receiverProfileEmail string, senderBaseProfileID int64, topic, text string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, receiverProfileEmail, senderBaseProfileID, topic, text)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessageUsecaseMockRecorder) SaveMessage(ctx, receiverProfileEmail, senderBaseProfileID, topic, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessageUsecase)(nil).SaveMessage), ctx, receiverProfileEmail, senderBaseProfileID, topic, text)
}

// SaveThread mocks base method.
func (m *MockMessageUsecase) SaveThread(ctx context.Context, messageID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveThread", ctx, messageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveThread indicates an expected call of SaveThread.
func (mr *MockMessageUsecaseMockRecorder) SaveThread(ctx, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveThread", reflect.TypeOf((*MockMessageUsecase)(nil).SaveThread), ctx, messageID)
}

// SaveThreadIdToMessage mocks base method.
func (m *MockMessageUsecase) SaveThreadIdToMessage(ctx context.Context, messageID, threadID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveThreadIdToMessage", ctx, messageID, threadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveThreadIdToMessage indicates an expected call of SaveThreadIdToMessage.
func (mr *MockMessageUsecaseMockRecorder) SaveThreadIdToMessage(ctx, messageID, threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveThreadIdToMessage", reflect.TypeOf((*MockMessageUsecase)(nil).SaveThreadIdToMessage), ctx, messageID, threadID)
}
