// Code generated by MockGen. DO NOT EDIT.
// Source: profile-page.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "2025_2_a4code/internal/domain"
	profile "2025_2_a4code/internal/usecase/profile"
	context "context"
	url "net/url"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockAvatarUsecase is a mock of AvatarUsecase interface.
type MockAvatarUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarUsecaseMockRecorder
}

// MockAvatarUsecaseMockRecorder is the mock recorder for MockAvatarUsecase.
type MockAvatarUsecaseMockRecorder struct {
	mock *MockAvatarUsecase
}

// NewMockAvatarUsecase creates a new mock instance.
func NewMockAvatarUsecase(ctrl *gomock.Controller) *MockAvatarUsecase {
	mock := &MockAvatarUsecase{ctrl: ctrl}
	mock.recorder = &MockAvatarUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarUsecase) EXPECT() *MockAvatarUsecaseMockRecorder {
	return m.recorder
}

// GetAvatarPresignedURL mocks base method.
func (m *MockAvatarUsecase) GetAvatarPresignedURL(ctx context.Context, objectName string, duration time.Duration) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarPresignedURL", ctx, objectName, duration)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarPresignedURL indicates an expected call of GetAvatarPresignedURL.
func (mr *MockAvatarUsecaseMockRecorder) GetAvatarPresignedURL(ctx, objectName, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarPresignedURL", reflect.TypeOf((*MockAvatarUsecase)(nil).GetAvatarPresignedURL), ctx, objectName, duration)
}

// MockProfileUsecase is a mock of ProfileUsecase interface.
type MockProfileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockProfileUsecaseMockRecorder
}

// MockProfileUsecaseMockRecorder is the mock recorder for MockProfileUsecase.
type MockProfileUsecaseMockRecorder struct {
	mock *MockProfileUsecase
}

// NewMockProfileUsecase creates a new mock instance.
func NewMockProfileUsecase(ctrl *gomock.Controller) *MockProfileUsecase {
	mock := &MockProfileUsecase{ctrl: ctrl}
	mock.recorder = &MockProfileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileUsecase) EXPECT() *MockProfileUsecaseMockRecorder {
	return m.recorder
}

// FindInfoByID mocks base method.
func (m *MockProfileUsecase) FindInfoByID(ctx context.Context, id int64) (domain.ProfileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInfoByID", ctx, id)
	ret0, _ := ret[0].(domain.ProfileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInfoByID indicates an expected call of FindInfoByID.
func (mr *MockProfileUsecaseMockRecorder) FindInfoByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInfoByID", reflect.TypeOf((*MockProfileUsecase)(nil).FindInfoByID), ctx, id)
}

// UpdateProfileInfo mocks base method.
func (m *MockProfileUsecase) UpdateProfileInfo(ctx context.Context, profileID int64, req profile.UpdateProfileRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfileInfo", ctx, profileID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfileInfo indicates an expected call of UpdateProfileInfo.
func (mr *MockProfileUsecaseMockRecorder) UpdateProfileInfo(ctx, profileID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileInfo", reflect.TypeOf((*MockProfileUsecase)(nil).UpdateProfileInfo), ctx, profileID, req)
}
