// Code generated by MockGen. DO NOT EDIT.
// Source: settings.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "2025_2_a4code/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProfileUsecase is a mock of ProfileUsecase interface.
type MockProfileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockProfileUsecaseMockRecorder
}

// MockProfileUsecaseMockRecorder is the mock recorder for MockProfileUsecase.
type MockProfileUsecaseMockRecorder struct {
	mock *MockProfileUsecase
}

// NewMockProfileUsecase creates a new mock instance.
func NewMockProfileUsecase(ctrl *gomock.Controller) *MockProfileUsecase {
	mock := &MockProfileUsecase{ctrl: ctrl}
	mock.recorder = &MockProfileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileUsecase) EXPECT() *MockProfileUsecaseMockRecorder {
	return m.recorder
}

// FindSettingsByProfileId mocks base method.
func (m *MockProfileUsecase) FindSettingsByProfileId(ctx context.Context, profileID int64) (domain.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSettingsByProfileId", ctx, profileID)
	ret0, _ := ret[0].(domain.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSettingsByProfileId indicates an expected call of FindSettingsByProfileId.
func (mr *MockProfileUsecaseMockRecorder) FindSettingsByProfileId(ctx, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSettingsByProfileId", reflect.TypeOf((*MockProfileUsecase)(nil).FindSettingsByProfileId), ctx, profileID)
}
