primary_hostname = mail.flintmail.ru
domainlist local_domains = flintmail.ru : localhost

acl_smtp_rcpt = accept
acl_smtp_data = accept

begin routers

lmtp_router:
  driver = accept
  domains = +local_domains
  transport = lmtp_transport

begin transports

lmtp_transport:
  driver = smtp
  protocol = lmtp
  hosts = mail-ingest
  port = 2525

begin retry
* * F,2h,15m; G,16h,1h,1.5; F,4d,6h

begin rewrite

begin authenticators
