primary_hostname = mail.flintmail.ru
domainlist local_domains = flintmail.ru : localhost
hostlist relay_from_hosts = 127.0.0.1 : ::1 : 10.0.0.0/8 : 172.16.0.0/12 : 192.168.0.0/16

# connection / concurrency guards
smtp_accept_max = 30
smtp_accept_max_per_host = 5
remote_max_parallel = 5
queue_run_max = 5
smtp_accept_max_per_connection = 20

# TLS
tls_advertise_hosts = *
tls_certificate = /etc/exim4/fullchain.pem
tls_privatekey = /etc/exim4/privkey.pem

acl_smtp_rcpt = acl_check_rcpt
acl_smtp_data = acl_check_data

begin acl

acl_check_rcpt:
  # allow local deliveries
  accept hosts = :
  accept authenticated = *
  accept hosts = +relay_from_hosts
  accept domains = +local_domains

  # otherwise deny relay
  deny message = relay not permitted

acl_check_data:
  accept

begin routers

lmtp_router:
  driver = accept
  domains = +local_domains
  transport = lmtp_transport

dnslookup_router:
  driver = dnslookup
  domains = ! +local_domains
  transport = remote_smtp
  no_more

begin transports

lmtp_transport:
  driver = smtp
  protocol = lmtp
  hosts = mail-ingest
  port = 2525

remote_smtp:
  driver = smtp
  dkim_domain = flintmail.ru
  dkim_selector = default
  dkim_private_key = /etc/exim4/dkim_private.key

begin retry
* * F,2h,15m; G,16h,1h,1.5; F,4d,6h

begin rewrite

begin authenticators
