// Code generated by MockGen. DO NOT EDIT.
// Source: message-page.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "2025_2_a4code/internal/domain"
	context "context"
	url "net/url"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageUsecase is a mock of MessageUsecase interface.
type MockMessageUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMessageUsecaseMockRecorder
}

// MockMessageUsecaseMockRecorder is the mock recorder for MockMessageUsecase.
type MockMessageUsecaseMockRecorder struct {
	mock *MockMessageUsecase
}

// NewMockMessageUsecase creates a new mock instance.
func NewMockMessageUsecase(ctrl *gomock.Controller) *MockMessageUsecase {
	mock := &MockMessageUsecase{ctrl: ctrl}
	mock.recorder = &MockMessageUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageUsecase) EXPECT() *MockMessageUsecaseMockRecorder {
	return m.recorder
}

// FindFullByMessageID mocks base method.
func (m *MockMessageUsecase) FindFullByMessageID(ctx context.Context, messageID, profileID int64) (domain.FullMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFullByMessageID", ctx, messageID, profileID)
	ret0, _ := ret[0].(domain.FullMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFullByMessageID indicates an expected call of FindFullByMessageID.
func (mr *MockMessageUsecaseMockRecorder) FindFullByMessageID(ctx, messageID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFullByMessageID", reflect.TypeOf((*MockMessageUsecase)(nil).FindFullByMessageID), ctx, messageID, profileID)
}

// MarkMessageAsRead mocks base method.
func (m *MockMessageUsecase) MarkMessageAsRead(ctx context.Context, messageID, profileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMessageAsRead", ctx, messageID, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMessageAsRead indicates an expected call of MarkMessageAsRead.
func (mr *MockMessageUsecaseMockRecorder) MarkMessageAsRead(ctx, messageID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMessageAsRead", reflect.TypeOf((*MockMessageUsecase)(nil).MarkMessageAsRead), ctx, messageID, profileID)
}

// MockAvatarUsecase is a mock of AvatarUsecase interface.
type MockAvatarUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarUsecaseMockRecorder
}

// MockAvatarUsecaseMockRecorder is the mock recorder for MockAvatarUsecase.
type MockAvatarUsecaseMockRecorder struct {
	mock *MockAvatarUsecase
}

// NewMockAvatarUsecase creates a new mock instance.
func NewMockAvatarUsecase(ctrl *gomock.Controller) *MockAvatarUsecase {
	mock := &MockAvatarUsecase{ctrl: ctrl}
	mock.recorder = &MockAvatarUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarUsecase) EXPECT() *MockAvatarUsecaseMockRecorder {
	return m.recorder
}

// GetAvatarPresignedURL mocks base method.
func (m *MockAvatarUsecase) GetAvatarPresignedURL(ctx context.Context, objectName string, duration time.Duration) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarPresignedURL", ctx, objectName, duration)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarPresignedURL indicates an expected call of GetAvatarPresignedURL.
func (mr *MockAvatarUsecaseMockRecorder) GetAvatarPresignedURL(ctx, objectName, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarPresignedURL", reflect.TypeOf((*MockAvatarUsecase)(nil).GetAvatarPresignedURL), ctx, objectName, duration)
}
