// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: messages.proto

package messagesproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender        *Sender                `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Snippet       string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Datetime      string                 `protobuf:"bytes,5,opt,name=datetime,proto3" json:"datetime,omitempty"`
	IsRead        string                 `protobuf:"bytes,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSender() *Sender {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Message) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Message) GetIsRead() string {
	if x != nil {
		return x.IsRead
	}
	return ""
}

type FullMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Datetime      string                 `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	ThreadId      string                 `protobuf:"bytes,4,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Sender        *Sender                `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Files         []*File                `protobuf:"bytes,6,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullMessage) Reset() {
	*x = FullMessage{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullMessage) ProtoMessage() {}

func (x *FullMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullMessage.ProtoReflect.Descriptor instead.
func (*FullMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *FullMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FullMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FullMessage) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *FullMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *FullMessage) GetSender() *Sender {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *FullMessage) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type Sender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sender) Reset() {
	*x = Sender{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sender) ProtoMessage() {}

func (x *Sender) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sender.ProtoReflect.Descriptor instead.
func (*Sender) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Sender) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Sender) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Sender) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type Receiver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Receiver) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	StoragePath   string                 `protobuf:"bytes,4,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *File) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *File) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

type PaginationInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HasNext           string                 `protobuf:"bytes,1,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	NextLastMessageId string                 `protobuf:"bytes,2,opt,name=next_last_message_id,json=nextLastMessageId,proto3" json:"next_last_message_id,omitempty"`
	NextLastDatetime  string                 `protobuf:"bytes,3,opt,name=next_last_datetime,json=nextLastDatetime,proto3" json:"next_last_datetime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PaginationInfo) GetHasNext() string {
	if x != nil {
		return x.HasNext
	}
	return ""
}

func (x *PaginationInfo) GetNextLastMessageId() string {
	if x != nil {
		return x.NextLastMessageId
	}
	return ""
}

func (x *PaginationInfo) GetNextLastDatetime() string {
	if x != nil {
		return x.NextLastDatetime
	}
	return ""
}

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	FolderName    string                 `protobuf:"bytes,2,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	FolderType    string                 `protobuf:"bytes,3,opt,name=folder_type,json=folderType,proto3" json:"folder_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Folder) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *Folder) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

func (x *Folder) GetFolderType() string {
	if x != nil {
		return x.FolderType
	}
	return ""
}

type MessagesInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageTotal  string                 `protobuf:"bytes,1,opt,name=message_total,json=messageTotal,proto3" json:"message_total,omitempty"`
	MessageUnread string                 `protobuf:"bytes,2,opt,name=message_unread,json=messageUnread,proto3" json:"message_unread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesInfo) Reset() {
	*x = MessagesInfo{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesInfo) ProtoMessage() {}

func (x *MessagesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesInfo.ProtoReflect.Descriptor instead.
func (*MessagesInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *MessagesInfo) GetMessageTotal() string {
	if x != nil {
		return x.MessageTotal
	}
	return ""
}

func (x *MessagesInfo) GetMessageUnread() string {
	if x != nil {
		return x.MessageUnread
	}
	return ""
}

// Основные методы для сообщений
type InboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastMessageId string                 `protobuf:"bytes,1,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	LastDatetime  string                 `protobuf:"bytes,2,opt,name=last_datetime,json=lastDatetime,proto3" json:"last_datetime,omitempty"`
	Limit         string                 `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxRequest) Reset() {
	*x = InboxRequest{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxRequest) ProtoMessage() {}

func (x *InboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxRequest.ProtoReflect.Descriptor instead.
func (*InboxRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *InboxRequest) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *InboxRequest) GetLastDatetime() string {
	if x != nil {
		return x.LastDatetime
	}
	return ""
}

func (x *InboxRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type InboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageTotal  string                 `protobuf:"bytes,1,opt,name=message_total,json=messageTotal,proto3" json:"message_total,omitempty"`
	MessageUnread string                 `protobuf:"bytes,2,opt,name=message_unread,json=messageUnread,proto3" json:"message_unread,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Pagination    *PaginationInfo        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxResponse) Reset() {
	*x = InboxResponse{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxResponse) ProtoMessage() {}

func (x *InboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxResponse.ProtoReflect.Descriptor instead.
func (*InboxResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *InboxResponse) GetMessageTotal() string {
	if x != nil {
		return x.MessageTotal
	}
	return ""
}

func (x *InboxResponse) GetMessageUnread() string {
	if x != nil {
		return x.MessageUnread
	}
	return ""
}

func (x *InboxResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *InboxResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type MessagePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePageRequest) Reset() {
	*x = MessagePageRequest{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePageRequest) ProtoMessage() {}

func (x *MessagePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePageRequest.ProtoReflect.Descriptor instead.
func (*MessagePageRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *MessagePageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type MessagePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *FullMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePageResponse) Reset() {
	*x = MessagePageResponse{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePageResponse) ProtoMessage() {}

func (x *MessagePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePageResponse.ProtoReflect.Descriptor instead.
func (*MessagePageResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *MessagePageResponse) GetMessage() *FullMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootMessageId string                 `protobuf:"bytes,1,opt,name=root_message_id,json=rootMessageId,proto3" json:"root_message_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ThreadRoot    string                 `protobuf:"bytes,4,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Receivers     []*Receiver            `protobuf:"bytes,5,rep,name=receivers,proto3" json:"receivers,omitempty"`
	Files         []*File                `protobuf:"bytes,6,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyRequest) Reset() {
	*x = ReplyRequest{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyRequest) ProtoMessage() {}

func (x *ReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyRequest.ProtoReflect.Descriptor instead.
func (*ReplyRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ReplyRequest) GetRootMessageId() string {
	if x != nil {
		return x.RootMessageId
	}
	return ""
}

func (x *ReplyRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ReplyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReplyRequest) GetThreadRoot() string {
	if x != nil {
		return x.ThreadRoot
	}
	return ""
}

func (x *ReplyRequest) GetReceivers() []*Receiver {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *ReplyRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type ReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyResponse) Reset() {
	*x = ReplyResponse{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyResponse) ProtoMessage() {}

func (x *ReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyResponse.ProtoReflect.Descriptor instead.
func (*ReplyResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Receivers     []*Receiver            `protobuf:"bytes,3,rep,name=receivers,proto3" json:"receivers,omitempty"`
	Files         []*File                `protobuf:"bytes,4,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *SendRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendRequest) GetReceivers() []*Receiver {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *SendRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *SendResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastMessageId string                 `protobuf:"bytes,1,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	LastDatetime  string                 `protobuf:"bytes,2,opt,name=last_datetime,json=lastDatetime,proto3" json:"last_datetime,omitempty"`
	Limit         string                 `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentRequest) Reset() {
	*x = SentRequest{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentRequest) ProtoMessage() {}

func (x *SentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentRequest.ProtoReflect.Descriptor instead.
func (*SentRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *SentRequest) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *SentRequest) GetLastDatetime() string {
	if x != nil {
		return x.LastDatetime
	}
	return ""
}

func (x *SentRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type SentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageTotal  string                 `protobuf:"bytes,1,opt,name=message_total,json=messageTotal,proto3" json:"message_total,omitempty"`
	MessageUnread string                 `protobuf:"bytes,2,opt,name=message_unread,json=messageUnread,proto3" json:"message_unread,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Pagination    *PaginationInfo        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentResponse) Reset() {
	*x = SentResponse{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentResponse) ProtoMessage() {}

func (x *SentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentResponse.ProtoReflect.Descriptor instead.
func (*SentResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *SentResponse) GetMessageTotal() string {
	if x != nil {
		return x.MessageTotal
	}
	return ""
}

func (x *SentResponse) GetMessageUnread() string {
	if x != nil {
		return x.MessageUnread
	}
	return ""
}

func (x *SentResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SentResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Методы для работы с сообщениями
type MarkAsSpamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsSpamRequest) Reset() {
	*x = MarkAsSpamRequest{}
	mi := &file_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsSpamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsSpamRequest) ProtoMessage() {}

func (x *MarkAsSpamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsSpamRequest.ProtoReflect.Descriptor instead.
func (*MarkAsSpamRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

func (x *MarkAsSpamRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type MarkAsSpamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsSpamResponse) Reset() {
	*x = MarkAsSpamResponse{}
	mi := &file_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsSpamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsSpamResponse) ProtoMessage() {}

func (x *MarkAsSpamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsSpamResponse.ProtoReflect.Descriptor instead.
func (*MarkAsSpamResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

type MoveToFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FolderId      string                 `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToFolderRequest) Reset() {
	*x = MoveToFolderRequest{}
	mi := &file_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToFolderRequest) ProtoMessage() {}

func (x *MoveToFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToFolderRequest.ProtoReflect.Descriptor instead.
func (*MoveToFolderRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20}
}

func (x *MoveToFolderRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MoveToFolderRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type MoveToFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToFolderResponse) Reset() {
	*x = MoveToFolderResponse{}
	mi := &file_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToFolderResponse) ProtoMessage() {}

func (x *MoveToFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToFolderResponse.ProtoReflect.Descriptor instead.
func (*MoveToFolderResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{21}
}

// Методы для папок
type CreateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderName    string                 `protobuf:"bytes,1,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{22}
}

func (x *CreateFolderRequest) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

type CreateFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	FolderName    string                 `protobuf:"bytes,2,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	FolderType    string                 `protobuf:"bytes,3,opt,name=folder_type,json=folderType,proto3" json:"folder_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderResponse) Reset() {
	*x = CreateFolderResponse{}
	mi := &file_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderResponse) ProtoMessage() {}

func (x *CreateFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderResponse.ProtoReflect.Descriptor instead.
func (*CreateFolderResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{23}
}

func (x *CreateFolderResponse) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *CreateFolderResponse) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

func (x *CreateFolderResponse) GetFolderType() string {
	if x != nil {
		return x.FolderType
	}
	return ""
}

type GetFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	LastMessageId string                 `protobuf:"bytes,2,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	LastDatetime  string                 `protobuf:"bytes,3,opt,name=last_datetime,json=lastDatetime,proto3" json:"last_datetime,omitempty"`
	Limit         string                 `protobuf:"bytes,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFolderRequest) Reset() {
	*x = GetFolderRequest{}
	mi := &file_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolderRequest) ProtoMessage() {}

func (x *GetFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolderRequest.ProtoReflect.Descriptor instead.
func (*GetFolderRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{24}
}

func (x *GetFolderRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *GetFolderRequest) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *GetFolderRequest) GetLastDatetime() string {
	if x != nil {
		return x.LastDatetime
	}
	return ""
}

func (x *GetFolderRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type GetFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageTotal  string                 `protobuf:"bytes,1,opt,name=message_total,json=messageTotal,proto3" json:"message_total,omitempty"`
	MessageUnread string                 `protobuf:"bytes,2,opt,name=message_unread,json=messageUnread,proto3" json:"message_unread,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Pagination    *PaginationInfo        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFolderResponse) Reset() {
	*x = GetFolderResponse{}
	mi := &file_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolderResponse) ProtoMessage() {}

func (x *GetFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolderResponse.ProtoReflect.Descriptor instead.
func (*GetFolderResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{25}
}

func (x *GetFolderResponse) GetMessageTotal() string {
	if x != nil {
		return x.MessageTotal
	}
	return ""
}

func (x *GetFolderResponse) GetMessageUnread() string {
	if x != nil {
		return x.MessageUnread
	}
	return ""
}

func (x *GetFolderResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetFolderResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetFoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoldersRequest) Reset() {
	*x = GetFoldersRequest{}
	mi := &file_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoldersRequest) ProtoMessage() {}

func (x *GetFoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoldersRequest.ProtoReflect.Descriptor instead.
func (*GetFoldersRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{26}
}

type GetFoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoldersResponse) Reset() {
	*x = GetFoldersResponse{}
	mi := &file_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoldersResponse) ProtoMessage() {}

func (x *GetFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoldersResponse.ProtoReflect.Descriptor instead.
func (*GetFoldersResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{27}
}

func (x *GetFoldersResponse) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

type RenameFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	NewFolderName string                 `protobuf:"bytes,2,opt,name=new_folder_name,json=newFolderName,proto3" json:"new_folder_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFolderRequest) Reset() {
	*x = RenameFolderRequest{}
	mi := &file_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFolderRequest) ProtoMessage() {}

func (x *RenameFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFolderRequest.ProtoReflect.Descriptor instead.
func (*RenameFolderRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{28}
}

func (x *RenameFolderRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *RenameFolderRequest) GetNewFolderName() string {
	if x != nil {
		return x.NewFolderName
	}
	return ""
}

type RenameFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	FolderName    string                 `protobuf:"bytes,2,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	FolderType    string                 `protobuf:"bytes,3,opt,name=folder_type,json=folderType,proto3" json:"folder_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFolderResponse) Reset() {
	*x = RenameFolderResponse{}
	mi := &file_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFolderResponse) ProtoMessage() {}

func (x *RenameFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFolderResponse.ProtoReflect.Descriptor instead.
func (*RenameFolderResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{29}
}

func (x *RenameFolderResponse) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *RenameFolderResponse) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

func (x *RenameFolderResponse) GetFolderType() string {
	if x != nil {
		return x.FolderType
	}
	return ""
}

type DeleteFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderRequest) Reset() {
	*x = DeleteFolderRequest{}
	mi := &file_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderRequest) ProtoMessage() {}

func (x *DeleteFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderRequest.ProtoReflect.Descriptor instead.
func (*DeleteFolderRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteFolderRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type DeleteFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderResponse) Reset() {
	*x = DeleteFolderResponse{}
	mi := &file_messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderResponse) ProtoMessage() {}

func (x *DeleteFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderResponse.ProtoReflect.Descriptor instead.
func (*DeleteFolderResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{31}
}

type DeleteMessageFromFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FolderId      string                 `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageFromFolderRequest) Reset() {
	*x = DeleteMessageFromFolderRequest{}
	mi := &file_messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageFromFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageFromFolderRequest) ProtoMessage() {}

func (x *DeleteMessageFromFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageFromFolderRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageFromFolderRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteMessageFromFolderRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeleteMessageFromFolderRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type DeleteMessageFromFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageFromFolderResponse) Reset() {
	*x = DeleteMessageFromFolderResponse{}
	mi := &file_messages_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageFromFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageFromFolderResponse) ProtoMessage() {}

func (x *DeleteMessageFromFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageFromFolderResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageFromFolderResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{33}
}

// Методы для черновиков
type SaveDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       string                 `protobuf:"bytes,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Receivers     []*Receiver            `protobuf:"bytes,5,rep,name=receivers,proto3" json:"receivers,omitempty"`
	Files         []*File                `protobuf:"bytes,6,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDraftRequest) Reset() {
	*x = SaveDraftRequest{}
	mi := &file_messages_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDraftRequest) ProtoMessage() {}

func (x *SaveDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDraftRequest.ProtoReflect.Descriptor instead.
func (*SaveDraftRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{34}
}

func (x *SaveDraftRequest) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

func (x *SaveDraftRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SaveDraftRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SaveDraftRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SaveDraftRequest) GetReceivers() []*Receiver {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *SaveDraftRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type SaveDraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       string                 `protobuf:"bytes,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDraftResponse) Reset() {
	*x = SaveDraftResponse{}
	mi := &file_messages_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDraftResponse) ProtoMessage() {}

func (x *SaveDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDraftResponse.ProtoReflect.Descriptor instead.
func (*SaveDraftResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{35}
}

func (x *SaveDraftResponse) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

type DeleteDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       string                 `protobuf:"bytes,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDraftRequest) Reset() {
	*x = DeleteDraftRequest{}
	mi := &file_messages_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDraftRequest) ProtoMessage() {}

func (x *DeleteDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDraftRequest.ProtoReflect.Descriptor instead.
func (*DeleteDraftRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteDraftRequest) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

type DeleteDraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDraftResponse) Reset() {
	*x = DeleteDraftResponse{}
	mi := &file_messages_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDraftResponse) ProtoMessage() {}

func (x *DeleteDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDraftResponse.ProtoReflect.Descriptor instead.
func (*DeleteDraftResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteDraftResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       string                 `protobuf:"bytes,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDraftRequest) Reset() {
	*x = SendDraftRequest{}
	mi := &file_messages_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDraftRequest) ProtoMessage() {}

func (x *SendDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDraftRequest.ProtoReflect.Descriptor instead.
func (*SendDraftRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{38}
}

func (x *SendDraftRequest) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

type SendDraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDraftResponse) Reset() {
	*x = SendDraftResponse{}
	mi := &file_messages_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDraftResponse) ProtoMessage() {}

func (x *SendDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDraftResponse.ProtoReflect.Descriptor instead.
func (*SendDraftResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{39}
}

func (x *SendDraftResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendDraftResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\rmessagesproto\"\xad\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x06sender\x18\x02 \x01(\v2\x15.messagesproto.SenderR\x06sender\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\x12\x1a\n" +
	"\bdatetime\x18\x05 \x01(\tR\bdatetime\x12\x17\n" +
	"\ais_read\x18\x06 \x01(\tR\x06isRead\"\xca\x01\n" +
	"\vFullMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bdatetime\x18\x03 \x01(\tR\bdatetime\x12\x1b\n" +
	"\tthread_id\x18\x04 \x01(\tR\bthreadId\x12-\n" +
	"\x06sender\x18\x05 \x01(\v2\x15.messagesproto.SenderR\x06sender\x12)\n" +
	"\x05files\x18\x06 \x03(\v2\x13.messagesproto.FileR\x05files\"R\n" +
	"\x06Sender\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\" \n" +
	"\bReceiver\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"n\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\x12!\n" +
	"\fstorage_path\x18\x04 \x01(\tR\vstoragePath\"\x8a\x01\n" +
	"\x0ePaginationInfo\x12\x19\n" +
	"\bhas_next\x18\x01 \x01(\tR\ahasNext\x12/\n" +
	"\x14next_last_message_id\x18\x02 \x01(\tR\x11nextLastMessageId\x12,\n" +
	"\x12next_last_datetime\x18\x03 \x01(\tR\x10nextLastDatetime\"g\n" +
	"\x06Folder\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x1f\n" +
	"\vfolder_name\x18\x02 \x01(\tR\n" +
	"folderName\x12\x1f\n" +
	"\vfolder_type\x18\x03 \x01(\tR\n" +
	"folderType\"Z\n" +
	"\fMessagesInfo\x12#\n" +
	"\rmessage_total\x18\x01 \x01(\tR\fmessageTotal\x12%\n" +
	"\x0emessage_unread\x18\x02 \x01(\tR\rmessageUnread\"q\n" +
	"\fInboxRequest\x12&\n" +
	"\x0flast_message_id\x18\x01 \x01(\tR\rlastMessageId\x12#\n" +
	"\rlast_datetime\x18\x02 \x01(\tR\flastDatetime\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\tR\x05limit\"\xce\x01\n" +
	"\rInboxResponse\x12#\n" +
	"\rmessage_total\x18\x01 \x01(\tR\fmessageTotal\x12%\n" +
	"\x0emessage_unread\x18\x02 \x01(\tR\rmessageUnread\x122\n" +
	"\bmessages\x18\x03 \x03(\v2\x16.messagesproto.MessageR\bmessages\x12=\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1d.messagesproto.PaginationInfoR\n" +
	"pagination\"3\n" +
	"\x12MessagePageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"K\n" +
	"\x13MessagePageResponse\x124\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.messagesproto.FullMessageR\amessage\"\xe3\x01\n" +
	"\fReplyRequest\x12&\n" +
	"\x0froot_message_id\x18\x01 \x01(\tR\rrootMessageId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1f\n" +
	"\vthread_root\x18\x04 \x01(\tR\n" +
	"threadRoot\x125\n" +
	"\treceivers\x18\x05 \x03(\v2\x17.messagesproto.ReceiverR\treceivers\x12)\n" +
	"\x05files\x18\x06 \x03(\v2\x13.messagesproto.FileR\x05files\".\n" +
	"\rReplyResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x99\x01\n" +
	"\vSendRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x125\n" +
	"\treceivers\x18\x03 \x03(\v2\x17.messagesproto.ReceiverR\treceivers\x12)\n" +
	"\x05files\x18\x04 \x03(\v2\x13.messagesproto.FileR\x05files\"-\n" +
	"\fSendResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"p\n" +
	"\vSentRequest\x12&\n" +
	"\x0flast_message_id\x18\x01 \x01(\tR\rlastMessageId\x12#\n" +
	"\rlast_datetime\x18\x02 \x01(\tR\flastDatetime\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\tR\x05limit\"\xcd\x01\n" +
	"\fSentResponse\x12#\n" +
	"\rmessage_total\x18\x01 \x01(\tR\fmessageTotal\x12%\n" +
	"\x0emessage_unread\x18\x02 \x01(\tR\rmessageUnread\x122\n" +
	"\bmessages\x18\x03 \x03(\v2\x16.messagesproto.MessageR\bmessages\x12=\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1d.messagesproto.PaginationInfoR\n" +
	"pagination\"2\n" +
	"\x11MarkAsSpamRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x14\n" +
	"\x12MarkAsSpamResponse\"Q\n" +
	"\x13MoveToFolderRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\"\x16\n" +
	"\x14MoveToFolderResponse\"6\n" +
	"\x13CreateFolderRequest\x12\x1f\n" +
	"\vfolder_name\x18\x01 \x01(\tR\n" +
	"folderName\"u\n" +
	"\x14CreateFolderResponse\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x1f\n" +
	"\vfolder_name\x18\x02 \x01(\tR\n" +
	"folderName\x12\x1f\n" +
	"\vfolder_type\x18\x03 \x01(\tR\n" +
	"folderType\"\x92\x01\n" +
	"\x10GetFolderRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12&\n" +
	"\x0flast_message_id\x18\x02 \x01(\tR\rlastMessageId\x12#\n" +
	"\rlast_datetime\x18\x03 \x01(\tR\flastDatetime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\tR\x05limit\"\xd2\x01\n" +
	"\x11GetFolderResponse\x12#\n" +
	"\rmessage_total\x18\x01 \x01(\tR\fmessageTotal\x12%\n" +
	"\x0emessage_unread\x18\x02 \x01(\tR\rmessageUnread\x122\n" +
	"\bmessages\x18\x03 \x03(\v2\x16.messagesproto.MessageR\bmessages\x12=\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1d.messagesproto.PaginationInfoR\n" +
	"pagination\"\x13\n" +
	"\x11GetFoldersRequest\"E\n" +
	"\x12GetFoldersResponse\x12/\n" +
	"\afolders\x18\x01 \x03(\v2\x15.messagesproto.FolderR\afolders\"Z\n" +
	"\x13RenameFolderRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12&\n" +
	"\x0fnew_folder_name\x18\x02 \x01(\tR\rnewFolderName\"u\n" +
	"\x14RenameFolderResponse\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x1f\n" +
	"\vfolder_name\x18\x02 \x01(\tR\n" +
	"folderName\x12\x1f\n" +
	"\vfolder_type\x18\x03 \x01(\tR\n" +
	"folderType\"2\n" +
	"\x13DeleteFolderRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\"\x16\n" +
	"\x14DeleteFolderResponse\"\\\n" +
	"\x1eDeleteMessageFromFolderRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\"!\n" +
	"\x1fDeleteMessageFromFolderResponse\"\xd6\x01\n" +
	"\x10SaveDraftRequest\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\tR\adraftId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x125\n" +
	"\treceivers\x18\x05 \x03(\v2\x17.messagesproto.ReceiverR\treceivers\x12)\n" +
	"\x05files\x18\x06 \x03(\v2\x13.messagesproto.FileR\x05files\".\n" +
	"\x11SaveDraftResponse\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\tR\adraftId\"/\n" +
	"\x12DeleteDraftRequest\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\tR\adraftId\"/\n" +
	"\x13DeleteDraftResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x10SendDraftRequest\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\tR\adraftId\"L\n" +
	"\x11SendDraftResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId2\xbb\n" +
	"\n" +
	"\x0fMessagesService\x12B\n" +
	"\x05Inbox\x12\x1b.messagesproto.InboxRequest\x1a\x1c.messagesproto.InboxResponse\x12T\n" +
	"\vMessagePage\x12!.messagesproto.MessagePageRequest\x1a\".messagesproto.MessagePageResponse\x12B\n" +
	"\x05Reply\x12\x1b.messagesproto.ReplyRequest\x1a\x1c.messagesproto.ReplyResponse\x12?\n" +
	"\x04Send\x12\x1a.messagesproto.SendRequest\x1a\x1b.messagesproto.SendResponse\x12?\n" +
	"\x04Sent\x12\x1a.messagesproto.SentRequest\x1a\x1b.messagesproto.SentResponse\x12Q\n" +
	"\n" +
	"MarkAsSpam\x12 .messagesproto.MarkAsSpamRequest\x1a!.messagesproto.MarkAsSpamResponse\x12W\n" +
	"\fMoveToFolder\x12\".messagesproto.MoveToFolderRequest\x1a#.messagesproto.MoveToFolderResponse\x12W\n" +
	"\fCreateFolder\x12\".messagesproto.CreateFolderRequest\x1a#.messagesproto.CreateFolderResponse\x12N\n" +
	"\tGetFolder\x12\x1f.messagesproto.GetFolderRequest\x1a .messagesproto.GetFolderResponse\x12Q\n" +
	"\n" +
	"GetFolders\x12 .messagesproto.GetFoldersRequest\x1a!.messagesproto.GetFoldersResponse\x12W\n" +
	"\fRenameFolder\x12\".messagesproto.RenameFolderRequest\x1a#.messagesproto.RenameFolderResponse\x12W\n" +
	"\fDeleteFolder\x12\".messagesproto.DeleteFolderRequest\x1a#.messagesproto.DeleteFolderResponse\x12x\n" +
	"\x17DeleteMessageFromFolder\x12-.messagesproto.DeleteMessageFromFolderRequest\x1a..messagesproto.DeleteMessageFromFolderResponse\x12N\n" +
	"\tSaveDraft\x12\x1f.messagesproto.SaveDraftRequest\x1a .messagesproto.SaveDraftResponse\x12T\n" +
	"\vDeleteDraft\x12!.messagesproto.DeleteDraftRequest\x1a\".messagesproto.DeleteDraftResponse\x12N\n" +
	"\tSendDraft\x12\x1f.messagesproto.SendDraftRequest\x1a .messagesproto.SendDraftResponseB\x11Z\x0f/;messagesprotob\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_messages_proto_goTypes = []any{
	(*Message)(nil),                         // 0: messagesproto.Message
	(*FullMessage)(nil),                     // 1: messagesproto.FullMessage
	(*Sender)(nil),                          // 2: messagesproto.Sender
	(*Receiver)(nil),                        // 3: messagesproto.Receiver
	(*File)(nil),                            // 4: messagesproto.File
	(*PaginationInfo)(nil),                  // 5: messagesproto.PaginationInfo
	(*Folder)(nil),                          // 6: messagesproto.Folder
	(*MessagesInfo)(nil),                    // 7: messagesproto.MessagesInfo
	(*InboxRequest)(nil),                    // 8: messagesproto.InboxRequest
	(*InboxResponse)(nil),                   // 9: messagesproto.InboxResponse
	(*MessagePageRequest)(nil),              // 10: messagesproto.MessagePageRequest
	(*MessagePageResponse)(nil),             // 11: messagesproto.MessagePageResponse
	(*ReplyRequest)(nil),                    // 12: messagesproto.ReplyRequest
	(*ReplyResponse)(nil),                   // 13: messagesproto.ReplyResponse
	(*SendRequest)(nil),                     // 14: messagesproto.SendRequest
	(*SendResponse)(nil),                    // 15: messagesproto.SendResponse
	(*SentRequest)(nil),                     // 16: messagesproto.SentRequest
	(*SentResponse)(nil),                    // 17: messagesproto.SentResponse
	(*MarkAsSpamRequest)(nil),               // 18: messagesproto.MarkAsSpamRequest
	(*MarkAsSpamResponse)(nil),              // 19: messagesproto.MarkAsSpamResponse
	(*MoveToFolderRequest)(nil),             // 20: messagesproto.MoveToFolderRequest
	(*MoveToFolderResponse)(nil),            // 21: messagesproto.MoveToFolderResponse
	(*CreateFolderRequest)(nil),             // 22: messagesproto.CreateFolderRequest
	(*CreateFolderResponse)(nil),            // 23: messagesproto.CreateFolderResponse
	(*GetFolderRequest)(nil),                // 24: messagesproto.GetFolderRequest
	(*GetFolderResponse)(nil),               // 25: messagesproto.GetFolderResponse
	(*GetFoldersRequest)(nil),               // 26: messagesproto.GetFoldersRequest
	(*GetFoldersResponse)(nil),              // 27: messagesproto.GetFoldersResponse
	(*RenameFolderRequest)(nil),             // 28: messagesproto.RenameFolderRequest
	(*RenameFolderResponse)(nil),            // 29: messagesproto.RenameFolderResponse
	(*DeleteFolderRequest)(nil),             // 30: messagesproto.DeleteFolderRequest
	(*DeleteFolderResponse)(nil),            // 31: messagesproto.DeleteFolderResponse
	(*DeleteMessageFromFolderRequest)(nil),  // 32: messagesproto.DeleteMessageFromFolderRequest
	(*DeleteMessageFromFolderResponse)(nil), // 33: messagesproto.DeleteMessageFromFolderResponse
	(*SaveDraftRequest)(nil),                // 34: messagesproto.SaveDraftRequest
	(*SaveDraftResponse)(nil),               // 35: messagesproto.SaveDraftResponse
	(*DeleteDraftRequest)(nil),              // 36: messagesproto.DeleteDraftRequest
	(*DeleteDraftResponse)(nil),             // 37: messagesproto.DeleteDraftResponse
	(*SendDraftRequest)(nil),                // 38: messagesproto.SendDraftRequest
	(*SendDraftResponse)(nil),               // 39: messagesproto.SendDraftResponse
}
var file_messages_proto_depIdxs = []int32{
	2,  // 0: messagesproto.Message.sender:type_name -> messagesproto.Sender
	2,  // 1: messagesproto.FullMessage.sender:type_name -> messagesproto.Sender
	4,  // 2: messagesproto.FullMessage.file:type_name -> messagesproto.File
	0,  // 3: messagesproto.InboxResponse.messages:type_name -> messagesproto.Message
	5,  // 4: messagesproto.InboxResponse.pagination:type_name -> messagesproto.PaginationInfo
	1,  // 5: messagesproto.MessagePageResponse.message:type_name -> messagesproto.FullMessage
	3,  // 6: messagesproto.ReplyRequest.receivers:type_name -> messagesproto.Receiver
	4,  // 7: messagesproto.ReplyRequest.file:type_name -> messagesproto.File
	3,  // 8: messagesproto.SendRequest.receivers:type_name -> messagesproto.Receiver
	4,  // 9: messagesproto.SendRequest.file:type_name -> messagesproto.File
	0,  // 10: messagesproto.SentResponse.messages:type_name -> messagesproto.Message
	5,  // 11: messagesproto.SentResponse.pagination:type_name -> messagesproto.PaginationInfo
	0,  // 12: messagesproto.GetFolderResponse.messages:type_name -> messagesproto.Message
	5,  // 13: messagesproto.GetFolderResponse.pagination:type_name -> messagesproto.PaginationInfo
	6,  // 14: messagesproto.GetFoldersResponse.folders:type_name -> messagesproto.Folder
	3,  // 15: messagesproto.SaveDraftRequest.receivers:type_name -> messagesproto.Receiver
	4,  // 16: messagesproto.SaveDraftRequest.file:type_name -> messagesproto.File
	8,  // 17: messagesproto.MessagesService.Inbox:input_type -> messagesproto.InboxRequest
	10, // 18: messagesproto.MessagesService.MessagePage:input_type -> messagesproto.MessagePageRequest
	12, // 19: messagesproto.MessagesService.Reply:input_type -> messagesproto.ReplyRequest
	14, // 20: messagesproto.MessagesService.Send:input_type -> messagesproto.SendRequest
	16, // 21: messagesproto.MessagesService.Sent:input_type -> messagesproto.SentRequest
	18, // 22: messagesproto.MessagesService.MarkAsSpam:input_type -> messagesproto.MarkAsSpamRequest
	20, // 23: messagesproto.MessagesService.MoveToFolder:input_type -> messagesproto.MoveToFolderRequest
	22, // 24: messagesproto.MessagesService.CreateFolder:input_type -> messagesproto.CreateFolderRequest
	24, // 25: messagesproto.MessagesService.GetFolder:input_type -> messagesproto.GetFolderRequest
	26, // 26: messagesproto.MessagesService.GetFolders:input_type -> messagesproto.GetFoldersRequest
	28, // 27: messagesproto.MessagesService.RenameFolder:input_type -> messagesproto.RenameFolderRequest
	30, // 28: messagesproto.MessagesService.DeleteFolder:input_type -> messagesproto.DeleteFolderRequest
	32, // 29: messagesproto.MessagesService.DeleteMessageFromFolder:input_type -> messagesproto.DeleteMessageFromFolderRequest
	34, // 30: messagesproto.MessagesService.SaveDraft:input_type -> messagesproto.SaveDraftRequest
	36, // 31: messagesproto.MessagesService.DeleteDraft:input_type -> messagesproto.DeleteDraftRequest
	38, // 32: messagesproto.MessagesService.SendDraft:input_type -> messagesproto.SendDraftRequest
	9,  // 33: messagesproto.MessagesService.Inbox:output_type -> messagesproto.InboxResponse
	11, // 34: messagesproto.MessagesService.MessagePage:output_type -> messagesproto.MessagePageResponse
	13, // 35: messagesproto.MessagesService.Reply:output_type -> messagesproto.ReplyResponse
	15, // 36: messagesproto.MessagesService.Send:output_type -> messagesproto.SendResponse
	17, // 37: messagesproto.MessagesService.Sent:output_type -> messagesproto.SentResponse
	19, // 38: messagesproto.MessagesService.MarkAsSpam:output_type -> messagesproto.MarkAsSpamResponse
	21, // 39: messagesproto.MessagesService.MoveToFolder:output_type -> messagesproto.MoveToFolderResponse
	23, // 40: messagesproto.MessagesService.CreateFolder:output_type -> messagesproto.CreateFolderResponse
	25, // 41: messagesproto.MessagesService.GetFolder:output_type -> messagesproto.GetFolderResponse
	27, // 42: messagesproto.MessagesService.GetFolders:output_type -> messagesproto.GetFoldersResponse
	29, // 43: messagesproto.MessagesService.RenameFolder:output_type -> messagesproto.RenameFolderResponse
	31, // 44: messagesproto.MessagesService.DeleteFolder:output_type -> messagesproto.DeleteFolderResponse
	33, // 45: messagesproto.MessagesService.DeleteMessageFromFolder:output_type -> messagesproto.DeleteMessageFromFolderResponse
	35, // 46: messagesproto.MessagesService.SaveDraft:output_type -> messagesproto.SaveDraftResponse
	37, // 47: messagesproto.MessagesService.DeleteDraft:output_type -> messagesproto.DeleteDraftResponse
	39, // 48: messagesproto.MessagesService.SendDraft:output_type -> messagesproto.SendDraftResponse
	33, // [33:49] is the sub-list for method output_type
	17, // [17:33] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
