// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: messages.proto

package messagesproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessagesService_Inbox_FullMethodName                   = "/messagesproto.MessagesService/Inbox"
	MessagesService_MessagePage_FullMethodName             = "/messagesproto.MessagesService/MessagePage"
	MessagesService_Reply_FullMethodName                   = "/messagesproto.MessagesService/Reply"
	MessagesService_Send_FullMethodName                    = "/messagesproto.MessagesService/Send"
	MessagesService_Sent_FullMethodName                    = "/messagesproto.MessagesService/Sent"
	MessagesService_MarkAsSpam_FullMethodName              = "/messagesproto.MessagesService/MarkAsSpam"
	MessagesService_MoveToFolder_FullMethodName            = "/messagesproto.MessagesService/MoveToFolder"
	MessagesService_CreateFolder_FullMethodName            = "/messagesproto.MessagesService/CreateFolder"
	MessagesService_GetFolder_FullMethodName               = "/messagesproto.MessagesService/GetFolder"
	MessagesService_GetFolders_FullMethodName              = "/messagesproto.MessagesService/GetFolders"
	MessagesService_RenameFolder_FullMethodName            = "/messagesproto.MessagesService/RenameFolder"
	MessagesService_DeleteFolder_FullMethodName            = "/messagesproto.MessagesService/DeleteFolder"
	MessagesService_DeleteMessageFromFolder_FullMethodName = "/messagesproto.MessagesService/DeleteMessageFromFolder"
	MessagesService_SaveDraft_FullMethodName               = "/messagesproto.MessagesService/SaveDraft"
	MessagesService_DeleteDraft_FullMethodName             = "/messagesproto.MessagesService/DeleteDraft"
	MessagesService_SendDraft_FullMethodName               = "/messagesproto.MessagesService/SendDraft"
)

// MessagesServiceClient is the client API for MessagesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessagesServiceClient interface {
	// Основные методы для сообщений
	Inbox(ctx context.Context, in *InboxRequest, opts ...grpc.CallOption) (*InboxResponse, error)
	MessagePage(ctx context.Context, in *MessagePageRequest, opts ...grpc.CallOption) (*MessagePageResponse, error)
	Reply(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*ReplyResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	Sent(ctx context.Context, in *SentRequest, opts ...grpc.CallOption) (*SentResponse, error)
	// Методы для работы с сообщениями
	MarkAsSpam(ctx context.Context, in *MarkAsSpamRequest, opts ...grpc.CallOption) (*MarkAsSpamResponse, error)
	MoveToFolder(ctx context.Context, in *MoveToFolderRequest, opts ...grpc.CallOption) (*MoveToFolderResponse, error)
	// Методы для папок
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error)
	GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*GetFolderResponse, error)
	GetFolders(ctx context.Context, in *GetFoldersRequest, opts ...grpc.CallOption) (*GetFoldersResponse, error)
	RenameFolder(ctx context.Context, in *RenameFolderRequest, opts ...grpc.CallOption) (*RenameFolderResponse, error)
	DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error)
	DeleteMessageFromFolder(ctx context.Context, in *DeleteMessageFromFolderRequest, opts ...grpc.CallOption) (*DeleteMessageFromFolderResponse, error)
	// Методы для черновиков
	SaveDraft(ctx context.Context, in *SaveDraftRequest, opts ...grpc.CallOption) (*SaveDraftResponse, error)
	DeleteDraft(ctx context.Context, in *DeleteDraftRequest, opts ...grpc.CallOption) (*DeleteDraftResponse, error)
	SendDraft(ctx context.Context, in *SendDraftRequest, opts ...grpc.CallOption) (*SendDraftResponse, error)
}

type messagesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagesServiceClient(cc grpc.ClientConnInterface) MessagesServiceClient {
	return &messagesServiceClient{cc}
}

func (c *messagesServiceClient) Inbox(ctx context.Context, in *InboxRequest, opts ...grpc.CallOption) (*InboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboxResponse)
	err := c.cc.Invoke(ctx, MessagesService_Inbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) MessagePage(ctx context.Context, in *MessagePageRequest, opts ...grpc.CallOption) (*MessagePageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagePageResponse)
	err := c.cc.Invoke(ctx, MessagesService_MessagePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) Reply(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*ReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyResponse)
	err := c.cc.Invoke(ctx, MessagesService_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, MessagesService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) Sent(ctx context.Context, in *SentRequest, opts ...grpc.CallOption) (*SentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentResponse)
	err := c.cc.Invoke(ctx, MessagesService_Sent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) MarkAsSpam(ctx context.Context, in *MarkAsSpamRequest, opts ...grpc.CallOption) (*MarkAsSpamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAsSpamResponse)
	err := c.cc.Invoke(ctx, MessagesService_MarkAsSpam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) MoveToFolder(ctx context.Context, in *MoveToFolderRequest, opts ...grpc.CallOption) (*MoveToFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveToFolderResponse)
	err := c.cc.Invoke(ctx, MessagesService_MoveToFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFolderResponse)
	err := c.cc.Invoke(ctx, MessagesService_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*GetFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFolderResponse)
	err := c.cc.Invoke(ctx, MessagesService_GetFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) GetFolders(ctx context.Context, in *GetFoldersRequest, opts ...grpc.CallOption) (*GetFoldersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFoldersResponse)
	err := c.cc.Invoke(ctx, MessagesService_GetFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) RenameFolder(ctx context.Context, in *RenameFolderRequest, opts ...grpc.CallOption) (*RenameFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFolderResponse)
	err := c.cc.Invoke(ctx, MessagesService_RenameFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFolderResponse)
	err := c.cc.Invoke(ctx, MessagesService_DeleteFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) DeleteMessageFromFolder(ctx context.Context, in *DeleteMessageFromFolderRequest, opts ...grpc.CallOption) (*DeleteMessageFromFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageFromFolderResponse)
	err := c.cc.Invoke(ctx, MessagesService_DeleteMessageFromFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) SaveDraft(ctx context.Context, in *SaveDraftRequest, opts ...grpc.CallOption) (*SaveDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveDraftResponse)
	err := c.cc.Invoke(ctx, MessagesService_SaveDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) DeleteDraft(ctx context.Context, in *DeleteDraftRequest, opts ...grpc.CallOption) (*DeleteDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDraftResponse)
	err := c.cc.Invoke(ctx, MessagesService_DeleteDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) SendDraft(ctx context.Context, in *SendDraftRequest, opts ...grpc.CallOption) (*SendDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendDraftResponse)
	err := c.cc.Invoke(ctx, MessagesService_SendDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagesServiceServer is the server API for MessagesService service.
// All implementations must embed UnimplementedMessagesServiceServer
// for forward compatibility.
type MessagesServiceServer interface {
	// Основные методы для сообщений
	Inbox(context.Context, *InboxRequest) (*InboxResponse, error)
	MessagePage(context.Context, *MessagePageRequest) (*MessagePageResponse, error)
	Reply(context.Context, *ReplyRequest) (*ReplyResponse, error)
	Send(context.Context, *SendRequest) (*SendResponse, error)
	Sent(context.Context, *SentRequest) (*SentResponse, error)
	// Методы для работы с сообщениями
	MarkAsSpam(context.Context, *MarkAsSpamRequest) (*MarkAsSpamResponse, error)
	MoveToFolder(context.Context, *MoveToFolderRequest) (*MoveToFolderResponse, error)
	// Методы для папок
	CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error)
	GetFolder(context.Context, *GetFolderRequest) (*GetFolderResponse, error)
	GetFolders(context.Context, *GetFoldersRequest) (*GetFoldersResponse, error)
	RenameFolder(context.Context, *RenameFolderRequest) (*RenameFolderResponse, error)
	DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error)
	DeleteMessageFromFolder(context.Context, *DeleteMessageFromFolderRequest) (*DeleteMessageFromFolderResponse, error)
	// Методы для черновиков
	SaveDraft(context.Context, *SaveDraftRequest) (*SaveDraftResponse, error)
	DeleteDraft(context.Context, *DeleteDraftRequest) (*DeleteDraftResponse, error)
	SendDraft(context.Context, *SendDraftRequest) (*SendDraftResponse, error)
	mustEmbedUnimplementedMessagesServiceServer()
}

// UnimplementedMessagesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessagesServiceServer struct{}

func (UnimplementedMessagesServiceServer) Inbox(context.Context, *InboxRequest) (*InboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inbox not implemented")
}
func (UnimplementedMessagesServiceServer) MessagePage(context.Context, *MessagePageRequest) (*MessagePageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessagePage not implemented")
}
func (UnimplementedMessagesServiceServer) Reply(context.Context, *ReplyRequest) (*ReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedMessagesServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMessagesServiceServer) Sent(context.Context, *SentRequest) (*SentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sent not implemented")
}
func (UnimplementedMessagesServiceServer) MarkAsSpam(context.Context, *MarkAsSpamRequest) (*MarkAsSpamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkAsSpam not implemented")
}
func (UnimplementedMessagesServiceServer) MoveToFolder(context.Context, *MoveToFolderRequest) (*MoveToFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveToFolder not implemented")
}
func (UnimplementedMessagesServiceServer) CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedMessagesServiceServer) GetFolder(context.Context, *GetFolderRequest) (*GetFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFolder not implemented")
}
func (UnimplementedMessagesServiceServer) GetFolders(context.Context, *GetFoldersRequest) (*GetFoldersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFolders not implemented")
}
func (UnimplementedMessagesServiceServer) RenameFolder(context.Context, *RenameFolderRequest) (*RenameFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameFolder not implemented")
}
func (UnimplementedMessagesServiceServer) DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFolder not implemented")
}
func (UnimplementedMessagesServiceServer) DeleteMessageFromFolder(context.Context, *DeleteMessageFromFolderRequest) (*DeleteMessageFromFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessageFromFolder not implemented")
}
func (UnimplementedMessagesServiceServer) SaveDraft(context.Context, *SaveDraftRequest) (*SaveDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDraft not implemented")
}
func (UnimplementedMessagesServiceServer) DeleteDraft(context.Context, *DeleteDraftRequest) (*DeleteDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDraft not implemented")
}
func (UnimplementedMessagesServiceServer) SendDraft(context.Context, *SendDraftRequest) (*SendDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDraft not implemented")
}
func (UnimplementedMessagesServiceServer) mustEmbedUnimplementedMessagesServiceServer() {}
func (UnimplementedMessagesServiceServer) testEmbeddedByValue()                         {}

// UnsafeMessagesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessagesServiceServer will
// result in compilation errors.
type UnsafeMessagesServiceServer interface {
	mustEmbedUnimplementedMessagesServiceServer()
}

func RegisterMessagesServiceServer(s grpc.ServiceRegistrar, srv MessagesServiceServer) {
	// If the following call pancis, it indicates UnimplementedMessagesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessagesService_ServiceDesc, srv)
}

func _MessagesService_Inbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).Inbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_Inbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).Inbox(ctx, req.(*InboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_MessagePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).MessagePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_MessagePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).MessagePage(ctx, req.(*MessagePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).Reply(ctx, req.(*ReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_Sent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).Sent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_Sent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).Sent(ctx, req.(*SentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_MarkAsSpam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAsSpamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).MarkAsSpam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_MarkAsSpam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).MarkAsSpam(ctx, req.(*MarkAsSpamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_MoveToFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveToFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).MoveToFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_MoveToFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).MoveToFolder(ctx, req.(*MoveToFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_GetFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).GetFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_GetFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).GetFolder(ctx, req.(*GetFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_GetFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).GetFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_GetFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).GetFolders(ctx, req.(*GetFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_RenameFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).RenameFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_RenameFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).RenameFolder(ctx, req.(*RenameFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_DeleteFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).DeleteFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_DeleteFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).DeleteFolder(ctx, req.(*DeleteFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_DeleteMessageFromFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageFromFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).DeleteMessageFromFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_DeleteMessageFromFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).DeleteMessageFromFolder(ctx, req.(*DeleteMessageFromFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_SaveDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).SaveDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_SaveDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).SaveDraft(ctx, req.(*SaveDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_DeleteDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).DeleteDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_DeleteDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).DeleteDraft(ctx, req.(*DeleteDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_SendDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).SendDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagesService_SendDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).SendDraft(ctx, req.(*SendDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessagesService_ServiceDesc is the grpc.ServiceDesc for MessagesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessagesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messagesproto.MessagesService",
	HandlerType: (*MessagesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inbox",
			Handler:    _MessagesService_Inbox_Handler,
		},
		{
			MethodName: "MessagePage",
			Handler:    _MessagesService_MessagePage_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _MessagesService_Reply_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _MessagesService_Send_Handler,
		},
		{
			MethodName: "Sent",
			Handler:    _MessagesService_Sent_Handler,
		},
		{
			MethodName: "MarkAsSpam",
			Handler:    _MessagesService_MarkAsSpam_Handler,
		},
		{
			MethodName: "MoveToFolder",
			Handler:    _MessagesService_MoveToFolder_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _MessagesService_CreateFolder_Handler,
		},
		{
			MethodName: "GetFolder",
			Handler:    _MessagesService_GetFolder_Handler,
		},
		{
			MethodName: "GetFolders",
			Handler:    _MessagesService_GetFolders_Handler,
		},
		{
			MethodName: "RenameFolder",
			Handler:    _MessagesService_RenameFolder_Handler,
		},
		{
			MethodName: "DeleteFolder",
			Handler:    _MessagesService_DeleteFolder_Handler,
		},
		{
			MethodName: "DeleteMessageFromFolder",
			Handler:    _MessagesService_DeleteMessageFromFolder_Handler,
		},
		{
			MethodName: "SaveDraft",
			Handler:    _MessagesService_SaveDraft_Handler,
		},
		{
			MethodName: "DeleteDraft",
			Handler:    _MessagesService_DeleteDraft_Handler,
		},
		{
			MethodName: "SendDraft",
			Handler:    _MessagesService_SendDraft_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
